import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
const source = readFileSync('build/installer.nsh', 'utf8').replace(/\r\n/g, '\n')
const macro = (name) => source.slice(source.indexOf(`!macro ${name}\n`), source.indexOf('!macroend', source.indexOf(`!macro ${name}\n`)))
describe('installer rollback boundaries', () => {
  it('retries cold-start readiness and preserves service registration on a failed check', () => {
    const install = macro('customInstall')
    expect(install).toContain('/TIMEOUT=30000')
    expect(install).toContain('$R6 < 5')
    const failure = install.slice(install.indexOf('FileOpen $R1 "C:\\ProgramData\\PlaytimePact\\install-health.log"'))
    expect(failure).toContain('Installation is not complete.')
    expect(failure).toContain('Abort')
    expect(failure).not.toContain('" uninstall')
    expect(macro('customUnInstall')).toContain('$R3 == 1060')
  })
  it('does not destroy protected policy selectors on uninstall or update', () => {
    expect(source).not.toMatch(/DeleteRegKey\s+HKLM\s+"Software\\PlaytimePact"/i)
  })
  it('authenticates before reversible shutdown and does not unregister before staging', () => {
    const auth = macro('customUnInit')
    expect(auth).toContain('PIN verification failed')
    expect(auth).toContain('resources\\PlaytimePactInstallerAuth.exe" --verify')
    expect(auth).not.toContain('powershell.exe')
    expect(auth).not.toContain(' stop')
    expect(auth).not.toContain('" uninstall')
    const stop = macro('customUnInstall')
    expect(stop).toContain('previous-watchdog-disabled.flag')
    expect(stop).not.toContain('DeleteRegKey')
    expect(stop).not.toContain('schtasks /delete')
    expect(stop).not.toContain('" uninstall')
  })
  it('uses a native, one-time-authorized fallback for legacy constrained-language upgrades', () => {
    const init = macro('customInit')
    expect(init).toContain('$R7 == "0.60.8"')
    expect(init).toContain('$R7 == "0.61.0-rc.1"')
    expect(init).toContain('SetRegView 64')
    expect(init).toContain('$R7 == "0.61.0-rc.2"')
    expect(init).toContain('$R7 == "0.61.0-rc.3"')
    expect(init).toContain('$R7 == "0.61.0-rc.4"')
    expect(init).toContain('$R7 == "0.61.0-rc.5"')
    expect(init).toContain('$R7 == "0.61.0-rc.6"')
    expect(init).toContain('$R7 == "0.61.0-rc.7"')
    expect(init).toContain('$R7 == "0.61.0-rc.8"')
    expect(init).toContain('$R7 == "0.61.0-rc.9"')
    expect(init).toContain('$PLUGINSDIR\\PlaytimePactInstallerAuth.exe" --authorize-upgrade')
    expect(init).not.toContain('CopyFiles /SILENT')
    expect(init).toContain('UninstallString')
  })
  it('waits for the disabled watchdog before killing the legacy app', () => {
    const helper = readFileSync('build/native/PlaytimePactInstallerAuth.cs', 'utf8')
    const disabled = helper.indexOf('watchdog-disabled.flag')
    const wait = helper.indexOf('Thread.Sleep(3500)', disabled)
    const kill = helper.indexOf('Process.GetProcessesByName("Playtime Pact")', disabled)
    expect(disabled).toBeGreaterThan(-1)
    expect(wait).toBeGreaterThan(disabled)
    expect(kill).toBeGreaterThan(wait)
  })
  it('restores files and the service before reporting a file-lock failure', () => {
    const remove = macro('customRemoveFiles')
    const stage = remove.indexOf('Call un.atomicRMDir')
    const restore = remove.indexOf('Call un.restoreFiles')
    const restart = remove.indexOf('PlaytimePactPrivilegedBroker.exe" start')
    const abort = remove.indexOf('Abort "Installation files are in use."')
    const unregister = remove.indexOf('sc.exe delete PlaytimePactPrivilegedBroker')
    expect(stage).toBeGreaterThanOrEqual(0)
    expect(restore).toBeGreaterThan(stage)
    expect(restart).toBeGreaterThan(restore)
    expect(abort).toBeGreaterThan(restart)
    expect(unregister).toBeGreaterThan(abort)
  })
  it('treats an absent or already-stopped protection service as safe to remove', () => {
    const stop = macro('customUnInstall')
    expect(stop).toContain('sc.exe stop PlaytimePactPrivilegedBroker')
    expect(stop).toContain('$R3 == 1060')
    expect(stop).toContain('$R3 == 1062')
  })
  it('repairs protected usage ACLs through the LocalSystem helper before service startup', () => {
    const install = macro('customInstall')
    expect(install).toContain('resources\\PlaytimePactInstallerAuth.exe" --repair-protection')
    expect(install.indexOf('--repair-protection')).toBeLessThan(install.indexOf('PlaytimePactPrivilegedBroker.exe" start'))
    expect(install).toContain('No protected data was removed')
  })
  it('repairs the protected parent PIN file ACL without replacing its contents', () => {
    const helper = readFileSync('build/native/PlaytimePactInstallerAuth.cs', 'utf8')
    const repair = helper.slice(helper.indexOf('private static bool RepairProtectionAccess()'), helper.indexOf('private static void SetProtectedDirectoryAccess'))
    expect(repair).toContain('SetProtectedDirectoryAccess(AdminDir)')
    expect(repair).toContain('Directory.GetFiles(AdminDir, "*", SearchOption.AllDirectories)')
    expect(repair).toContain('SetProtectedFileAccess(file)')
    expect(repair.indexOf('SetProtectedDirectoryAccess(AdminDir)')).toBeLessThan(repair.indexOf('Directory.CreateDirectory(accounting)'))
    expect(repair).not.toContain('WriteAllText(SecretPath')
  })
  it('restores shared session history permissions without deleting records', () => {
    const helper = readFileSync('build/native/PlaytimePactInstallerAuth.cs', 'utf8')
    const repair = helper.slice(helper.indexOf('private static bool RepairProtectionAccess()'), helper.indexOf('private static void SetProtectedDirectoryAccess'))
    expect(repair).toContain('SetSharedDataDirectoryAccess(data)')
    expect(repair).toContain('Directory.GetFiles(data, "*", SearchOption.AllDirectories)')
    expect(repair).toContain('SetSharedDataFileAccess(file)')
    expect(helper).toContain('new FileSystemAccessRule(users, FileSystemRights.Modify, AccessControlType.Allow)')
    expect(repair).not.toContain('File.Delete(')
  })
  it('takes damaged protected files into LocalSystem ownership before ACL repair', () => {
    const helper = readFileSync('build/native/PlaytimePactInstallerAuth.cs', 'utf8')
    const fallback = helper.slice(helper.indexOf('private static bool EnsureSystemFullControl'), helper.indexOf('private static bool IsDigits'))
    expect(fallback).toContain('RunQuiet("takeown.exe", "/F " + quoted, 10000)')
    expect(fallback).not.toContain('quoted + " /A"')
    expect(fallback).toContain('if (owner != 0 && !tookSystemOwnership && !allowAdministratorsOwner)')
  })
})
