package com.playtimepact.parent;

import android.content.Context;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** Authoritative parent approval state; mutations are never derived from the local cache. */
public final class ApprovalRepository implements AutoCloseable {
  public static final int DEFAULT_APPROVAL_MINUTES=20, MIN_APPROVAL_MINUTES=1, MAX_APPROVAL_MINUTES=240;
  private static final long STALE_AFTER_MS=5*60*1000L;
  private final Context context; private final RemoteApi api; private final ExecutorService worker; private final Executor callbackExecutor; private volatile State cached;
  public ApprovalRepository(Context context,Executor callbackExecutor){this(context,new RemoteApi(new PairingStore(context),new SecureIdentity(context)),Executors.newSingleThreadExecutor(),callbackExecutor);}
  public ApprovalRepository(RemoteApi api,Executor worker,Executor callbackExecutor){this(null,api,worker,callbackExecutor);}
  private ApprovalRepository(Context context,RemoteApi api,Executor worker,Executor callbackExecutor){if(api==null||worker==null||callbackExecutor==null)throw new IllegalArgumentException("Executors and API are required");this.context=context==null?null:context.getApplicationContext();this.api=api;this.callbackExecutor=callbackExecutor;if(!(worker instanceof ExecutorService))throw new IllegalArgumentException("Worker must be an ExecutorService");this.worker=(ExecutorService)worker;}
  public State getCachedState(){State s=cached;if(s==null)return new State(Status.OFFLINE,Collections.<Request>emptyList(),Collections.<Device>emptyList(),Collections.<Allowance>emptyList(),0,0,0,"","",null);return (s.getStatus()==Status.ONLINE&&System.currentTimeMillis()-s.getFetchedAtMillis()>STALE_AFTER_MS?s.withStatus(Status.STALE,null):s).asCached();}
  public State markSyncRequired(){State p=cached;cached=p==null?new State(Status.STALE,Collections.<Request>emptyList(),Collections.<Device>emptyList(),Collections.<Allowance>emptyList(),0,0,0,"","","새 요청 신호: 서버 새로고침 필요"):p.withStatus(Status.STALE,"새 요청 신호: 서버 새로고침 필요");return cached;}
  public void refresh(Callback<State> cb){execute(cb,()->cache(api.getState()));}
  public void approve(String id,int minutes,Callback<State>cb){mutate(id,cb,()->api.approve(id,clampMinutes(minutes)));} public void approveDefault(String id,Callback<State>cb){approve(id,DEFAULT_APPROVAL_MINUTES,cb);} public void rejectPersonally(String id,Callback<State>cb){mutate(id,cb,()->api.rejectPersonally(id));} public void revokeDevice(String id,Callback<State>cb){mutate(id,cb,()->api.revokeDevice(id));}
  public void setTodayAllowance(String pcId,String gameId,long expectedVersion,int totalMinutes,Callback<Allowance> cb){if(pcId==null||pcId.trim().isEmpty()||gameId==null||gameId.trim().isEmpty()||expectedVersion<0||totalMinutes<0) {fail(cb,new IllegalArgumentException("Invalid allowance edit"));return;} execute(cb,()->{requirePrivilegedVersion();return api.setTodayAllowance(pcId,gameId,expectedVersion,Math.multiplyExact(totalMinutes,60));});}
  public void registerFcmToken(String token,long version,Callback<Void>cb){if(token==null||token.trim().isEmpty()||version<=0){fail(cb,new IllegalArgumentException("Invalid FCM token"));return;}execute(cb,()->{api.registerFcmToken(token,version);return null;});}
  public void resetMembership(Callback<State>cb){mutate("membership-reset",cb,()->{api.resetMembership();if(context!=null)ApprovalMessagingService.clearToken(context);});}
  public void deleteHousehold(Callback<Void>cb){execute(cb,()->{requirePrivilegedVersion();api.deleteHousehold();if(context!=null)ApprovalMessagingService.clearToken(context);cached=null;return null;});}
  public void disconnect(Callback<Void>cb){execute(cb,()->{if(context!=null){ApprovalMessagingService.TokenState token=ApprovalMessagingService.loadToken(context);if(token!=null)api.revokeFcmToken(token.version);}api.clearPairing();if(context!=null)ApprovalMessagingService.clearToken(context);cached=null;return null;});}
  public static int clampMinutes(int m){return Math.max(MIN_APPROVAL_MINUTES,Math.min(MAX_APPROVAL_MINUTES,m));}
  private State cache(ServerState s){State r=new State(Status.ONLINE,s.getRequests(),s.getDevices(),s.getAllowances(),s.getTodayTotalMinutes(),System.currentTimeMillis(),s.getServerTimeMillis(),s.getLocalDay(),s.getTimeZone(),null,true);cached=r;return r;}
  private void mutate(String id,Callback<State>cb,Mutation m){if(id==null||id.trim().isEmpty()){fail(cb,new IllegalArgumentException("ID is required"));return;}execute(cb,()->{requirePrivilegedVersion();m.apply();return cache(api.getState());});}
  private <T>void execute(Callback<T>cb,Operation<T>op){worker.execute(()->{try{T r=op.run();callbackExecutor.execute(()->cb.onSuccess(r));}catch(Exception e){cacheFailure(e);callbackExecutor.execute(()->cb.onFailure(e));}});} private void fail(Callback<?> cb,Throwable e){callbackExecutor.execute(()->cb.onFailure(e));}private void cacheFailure(Exception e){State p=cached;Status s=e instanceof IOException?(p==null?Status.OFFLINE:Status.STALE):Status.ERROR;cached=p==null?new State(s,Collections.<Request>emptyList(),Collections.<Device>emptyList(),Collections.<Allowance>emptyList(),0,0,0,"","",e.getMessage()):p.withStatus(s,e.getMessage());}
  private void requirePrivilegedVersion() throws Exception { if(context==null) return; if(UpdateVerifier.isForegroundPolicyRefreshPending(context)) throw new SecurityException("Signed update policy refresh is in progress; parental changes remain locked"); if(!UpdateVerifier.isPolicyKnown(context)) throw new SecurityException("Signed update policy is unavailable offline; parental changes remain locked"); long required=UpdateVerifier.minimumSupportedVersion(context); long installed=context.getPackageManager().getPackageInfo(context.getPackageName(),0).getLongVersionCode(); if(required>installed) throw new SecurityException("A signed app update is required before changing parental controls"); }
  @Override public void close(){worker.shutdownNow();} private interface Operation<T>{T run()throws Exception;}private interface Mutation{void apply()throws Exception;}public interface Callback<T>{void onSuccess(T v);void onFailure(Throwable e);}public enum Status{ONLINE,OFFLINE,STALE,ERROR}
  public static final class Allowance{private final String pcId,gameId,localDay,timeZone;private final int totalSeconds,committedSeconds,reservedSeconds;private final long version,serverNowMs;public Allowance(String p,String g,String d,String z,int t,int c,int r,long v,long s){pcId=p;gameId=g;localDay=d;timeZone=z;totalSeconds=t;committedSeconds=c;reservedSeconds=r;version=v;serverNowMs=s;}public String getPcId(){return pcId;}public String getGameId(){return gameId;}public String getLocalDay(){return localDay;}public String getTimeZone(){return timeZone;}public int getTotalSeconds(){return totalSeconds;}public int getCommittedSeconds(){return committedSeconds;}public int getReservedSeconds(){return reservedSeconds;}public long getVersion(){return version;}public long getServerNowMs(){return serverNowMs;}}
  public static final class Request{private final String id,childName,gameName,deviceName,status,personalDecision;private final long createdAtMillis,expiresAtMillis;private final int todayUsedMinutes,todayLimitMinutes;public Request(String i,String c,String g,String d,String s,String p,long a,long e,int u,int l){id=i;childName=c;gameName=g;deviceName=d;status=s;personalDecision=p;createdAtMillis=a;expiresAtMillis=e;todayUsedMinutes=u;todayLimitMinutes=l;}public String getId(){return id;}public String getChildName(){return childName;}public String getGameName(){return gameName;}public String getDeviceName(){return deviceName;}public String getStatus(){return status;}public String getPersonalDecision(){return personalDecision;}public long getCreatedAtMillis(){return createdAtMillis;}public long getExpiresAtMillis(){return expiresAtMillis;}public int getTodayUsedMinutes(){return todayUsedMinutes;}public int getTodayLimitMinutes(){return todayLimitMinutes;}}
  public static final class Device{private final String id,name,platform,status;private final long lastSeenMillis;public Device(String i,String n,String p,String s,long l){id=i;name=n;platform=p;status=s;lastSeenMillis=l;}public String getId(){return id;}public String getName(){return name;}public String getPlatform(){return platform;}public String getStatus(){return status;}public long getLastSeenMillis(){return lastSeenMillis;}}
  public static final class State{private final Status status;private final List<Request>requests;private final List<Device>devices;private final List<Allowance>allowances;private final int todayTotalMinutes;private final long fetchedAtMillis,serverTimeMillis;private final String localDay,timeZone,error;private final boolean freshNetworkReceipt;public State(Status s,List<Request>r,List<Device>d,List<Allowance>a,int t,long f,long time,String day,String zone,String e){this(s,r,d,a,t,f,time,day,zone,e,false);}private State(Status s,List<Request>r,List<Device>d,List<Allowance>a,int t,long f,long time,String day,String zone,String e,boolean fresh){status=s;requests=Collections.unmodifiableList(new ArrayList<>(r));devices=Collections.unmodifiableList(new ArrayList<>(d));allowances=Collections.unmodifiableList(new ArrayList<>(a));todayTotalMinutes=t;fetchedAtMillis=f;serverTimeMillis=time;localDay=day;timeZone=zone;error=e;freshNetworkReceipt=fresh;}private State withStatus(Status s,String e){return new State(s,requests,devices,allowances,todayTotalMinutes,fetchedAtMillis,serverTimeMillis,localDay,timeZone,e,false);}private State asCached(){return freshNetworkReceipt?new State(status,requests,devices,allowances,todayTotalMinutes,fetchedAtMillis,serverTimeMillis,localDay,timeZone,error,false):this;}public Status getStatus(){return status;}public List<Request>getRequests(){return requests;}public List<Device>getDevices(){return devices;}public List<Allowance>getAllowances(){return allowances;}public int getTodayTotalMinutes(){return todayTotalMinutes;}public long getFetchedAtMillis(){return fetchedAtMillis;}public long getServerTimeMillis(){return serverTimeMillis;}public String getLocalDay(){return localDay;}public String getTimeZone(){return timeZone;}public String getError(){return error;}public boolean isFreshNetworkReceipt(){return freshNetworkReceipt;}}
  public static final class ServerState{private final List<Request>requests;private final List<Device>devices;private final List<Allowance>allowances;private final int todayTotalMinutes;private final long serverTimeMillis;private final String localDay,timeZone;public ServerState(List<Request>r,List<Device>d,List<Allowance>a,int t,long time,String day,String zone){requests=Collections.unmodifiableList(new ArrayList<>(r));devices=Collections.unmodifiableList(new ArrayList<>(d));allowances=Collections.unmodifiableList(new ArrayList<>(a));todayTotalMinutes=t;serverTimeMillis=time;localDay=day;timeZone=zone;}public List<Request>getRequests(){return requests;}public List<Device>getDevices(){return devices;}public List<Allowance>getAllowances(){return allowances;}public int getTodayTotalMinutes(){return todayTotalMinutes;}public long getServerTimeMillis(){return serverTimeMillis;}public String getLocalDay(){return localDay;}public String getTimeZone(){return timeZone;}}
}
