package com.playtimepact.parent;

import android.net.Uri;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;

import javax.net.ssl.HttpsURLConnection;

/** Minimal HTTPS client. Server state and versioned allowance mutations are authoritative. */
public final class RemoteApi {
  private static final int CONNECT_TIMEOUT_MS = 10_000, READ_TIMEOUT_MS = 15_000, MAX_RESPONSE_BYTES = 1_048_576;
  private final PairingStore pairingStore; private final SecureIdentity identity;
  public RemoteApi(PairingStore pairingStore, SecureIdentity identity) { if(pairingStore==null||identity==null) throw new IllegalArgumentException("Identity and pairing store are required"); this.pairingStore=pairingStore; this.identity=identity; }
  public void pair(String pairingUri) throws ApiException { try { PairingStore.Pairing pairing=PairingStore.parsePairingUri(pairingUri); JSONObject body=new JSONObject(); body.put("householdId",pairing.getHouseholdId()); body.put("parentId",pairing.getParentId()); body.put("token",pairing.getToken()); body.put("publicJwk",new JSONObject(identity.publicJwk())); pairingStore.save(pairingRequest(pairing,body)); } catch(Exception e) { throw apiError("Pairing failed",e); } }
  public ApprovalRepository.ServerState getState() throws ApiException { PairingStore.Pairing p=requirePairing(); try { return parseState(request(p,"GET","/v1/parent/state?householdId="+id(p.getHouseholdId()),null,null)); } catch(JSONException e) { throw new ApiException("Invalid server state",e); } }
  public ApprovalRepository.Request getRequest(String requestId) throws ApiException { PairingStore.Pairing p=requirePairing(); try{return parseRequest(request(p,"GET","/v1/request?householdId="+id(p.getHouseholdId())+"&requestId="+id(requestId),null,null));}catch(JSONException e){throw new ApiException("Invalid request response",e);} }
  public void approve(String requestId,int minutes) throws ApiException { mutate("/v1/approve",body("requestId",requestId,"minutes",ApprovalRepository.clampMinutes(minutes))); }
  public void rejectPersonally(String requestId) throws ApiException { mutate("/v1/reject",body("requestId",requestId)); }
  public void revokeDevice(String deviceId) throws ApiException { PairingStore.Pairing p=requirePairing(); request(p,"DELETE","/v1/parents",body("parentId",deviceId),null); }
  public ApprovalRepository.Allowance setTodayAllowance(String pcId,String gameId,long expectedVersion,int totalSeconds) throws ApiException { PairingStore.Pairing p=requirePairing(); JSONObject response=request(p,"POST","/v1/allowances",body("pcId",pcId,"gameId",gameId,"expectedVersion",expectedVersion,"totalSeconds",totalSeconds),null); try{return parseAllowance(response.getJSONObject("allowance"),response.getLong("serverNowMs"));}catch(JSONException e){throw new ApiException("Invalid allowance response",e);} }
  public void registerFcmToken(String token,long tokenVersion) throws ApiException { PairingStore.Pairing p=requirePairing(); try { JSONObject envelope=request(p,"POST","/v1/fcm-tokens",body("token",token,"tokenVersion",tokenVersion),null); JSONObject receipt=envelope.getJSONObject("fcm_token"); if(!p.getHouseholdId().equals(receipt.getString("household_id"))||!p.getParentId().equals(receipt.getString("parent_id"))||receipt.getLong("token_version")!=tokenVersion||!"active".equals(receipt.getString("status")))throw new ApiException("FCM registration receipt mismatch"); } catch(ApiException e){throw e;}catch(Exception e){throw apiError("Invalid FCM registration receipt",e);} }
  public void revokeFcmToken(long tokenVersion) throws ApiException { try { JSONObject envelope=request(requirePairing(),"DELETE","/v1/fcm-tokens",body("tokenVersion",tokenVersion),null); JSONObject receipt=envelope.getJSONObject("fcm_token"); if(receipt.getLong("token_version")!=tokenVersion||!"revoked".equals(receipt.getString("status")))throw new ApiException("FCM revoke receipt mismatch"); } catch(ApiException e){throw e;}catch(Exception e){throw apiError("Invalid FCM revoke receipt",e);} }
  public void resetMembership() throws ApiException { PairingStore.Pairing p=requirePairing(); try { String key=p.getPendingResetOperationKey(); if(key==null){key=UUID.randomUUID().toString();p=p.withPendingReset(key);pairingStore.save(p);} JSONObject receipt;try{receipt=request(p,"GET","/v1/reset/reconcile?householdId="+id(p.getHouseholdId()),null,key);}catch(ApiException unavailable){receipt=request(p,"POST","/v1/reset",body("recoveryParentId",p.getParentId(),"recoveryPublicJwk",new JSONObject(identity.publicJwk())),key);} if(!"reset".equals(receipt.getString("operation"))||!p.getHouseholdId().equals(receipt.getString("household_id"))||!p.getParentId().equals(receipt.getString("parent_id")))throw new ApiException("Reset receipt identity mismatch");pairingStore.save(p.withEpochs(receipt.getLong("membership_epoch"),receipt.getLong("service_epoch")));}catch(ApiException e){throw e;}catch(Exception e){throw apiError("Unable to reset membership",e);} }
  public void deleteHousehold() throws ApiException { PairingStore.Pairing p=requirePairing(); try { String key=p.getPendingDeleteOperationKey();if(key==null){key=UUID.randomUUID().toString();p=p.withPendingDelete(key);pairingStore.save(p);}JSONObject receipt;try{receipt=request(p,"GET","/v1/delete/reconcile?householdId="+id(p.getHouseholdId()),null,key);}catch(ApiException unavailable){receipt=request(p,"DELETE","/v1/household",body(),key);}if(!"delete".equals(receipt.getString("operation"))||!p.getHouseholdId().equals(receipt.getString("household_id"))||!key.equals(receipt.getString("last_operation_key")))throw new ApiException("Delete receipt identity mismatch");pairingStore.clear();}catch(ApiException e){throw e;}catch(Exception e){throw apiError("Unable to delete household",e);} }
  public void clearPairing() { pairingStore.clear(); }
  /** Replays a durable lifecycle intent after process restart before normal UI mutations. */
  public void reconcilePendingLifecycle() throws ApiException {
    PairingStore.Pairing p=requirePairing();
    if(p.getPendingDeleteOperationKey()!=null) { deleteHousehold(); return; }
    if(p.getPendingResetOperationKey()!=null) resetMembership();
  }
  private void mutate(String path,JSONObject body) throws ApiException { PairingStore.Pairing p=requirePairing(); request(p,"POST",path,body,null); }
  private JSONObject body(Object... pairs) throws ApiException { try { PairingStore.Pairing p=requirePairing(); JSONObject b=new JSONObject(); b.put("householdId",p.getHouseholdId()); for(int i=0;i<pairs.length;i+=2)b.put((String)pairs[i],pairs[i+1]); return b; }catch(Exception e){throw apiError("Invalid request",e);} }
  private PairingStore.Pairing requirePairing() throws ApiException { try { PairingStore.Pairing p=pairingStore.load(); if(p==null)throw new ApiException("Parent device is not paired"); return p; }catch(PairingStore.PairingException e){throw new ApiException("Parent device is not paired",e);} }
  private JSONObject request(PairingStore.Pairing p,String method,String path,JSONObject body,String key) throws ApiException { HttpsURLConnection c=null; try { String canonical=body==null?"":canonicalJson(body); URL url=new URL(p.getBaseUrl()+path); c=(HttpsURLConnection)url.openConnection(); c.setConnectTimeout(CONNECT_TIMEOUT_MS);c.setReadTimeout(READ_TIMEOUT_MS);c.setUseCaches(false);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json"); String idempotency=key==null?UUID.randomUUID().toString():key; SecureIdentity.Proof proof=identity.signProof(method,url.toString(),canonical,p.getParentId(),p.getMembershipEpoch(),p.getServiceEpoch(),idempotency,BuildConfig.VERSION_CODE); c.setRequestProperty("Authorization","Bearer "+proof.flattenedJson()); if(body!=null){byte[] bytes=canonical.getBytes(StandardCharsets.UTF_8);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setFixedLengthStreamingMode(bytes.length);c.getOutputStream().write(bytes);c.getOutputStream().close();} int status=c.getResponseCode();byte[] response=read(status>=200&&status<300?c.getInputStream():c.getErrorStream()); if(status<200||status>=300)throw new ConflictException("Server rejected request (HTTP "+status+")",status,response.length==0?null:new JSONObject(new String(response,StandardCharsets.UTF_8))); return response.length==0?new JSONObject():new JSONObject(new String(response,StandardCharsets.UTF_8)); }catch(ApiException e){throw e;}catch(Exception e){throw apiError("Network request failed",e);}finally{if(c!=null)c.disconnect();} }
  private PairingStore.Pairing pairingRequest(PairingStore.Pairing p,JSONObject body) throws ApiException { HttpsURLConnection c=null;try{String canonical=canonicalJson(body);URL url=new URL(p.getBaseUrl()+"/v1/pair");c=(HttpsURLConnection)url.openConnection();c.setConnectTimeout(CONNECT_TIMEOUT_MS);c.setReadTimeout(READ_TIMEOUT_MS);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setRequestProperty("X-Pairing-Token",p.getToken());byte[] bytes=canonical.getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(bytes.length);c.getOutputStream().write(bytes);c.getOutputStream().close();int status=c.getResponseCode();byte[] response=read(status>=200&&status<300?c.getInputStream():c.getErrorStream());if(status<200||status>=300)throw new ApiException("Server rejected pairing (HTTP "+status+")");JSONObject accepted=new JSONObject(new String(response,StandardCharsets.UTF_8));if(!p.getHouseholdId().equals(accepted.getString("householdId"))||!p.getParentId().equals(accepted.getString("parentId")))throw new ApiException("Pairing response identity mismatch");return new PairingStore.Pairing(p.getBaseUrl(),p.getHouseholdId(),p.getParentId(),"",accepted.getLong("membershipEpoch"),accepted.getLong("serviceEpoch"));}catch(ApiException e){throw e;}catch(Exception e){throw apiError("Pairing network request failed",e);}finally{if(c!=null)c.disconnect();}}
  private static byte[] read(java.io.InputStream input)throws IOException{if(input==null)return new byte[0];try(BufferedInputStream in=new BufferedInputStream(input);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>MAX_RESPONSE_BYTES)throw new IOException("Response too large");out.write(b,0,n);}return out.toByteArray();}}
  static String canonicalJson(JSONObject object)throws JSONException{List<String> names=new ArrayList<>();Iterator<String> keys=object.keys();while(keys.hasNext())names.add(keys.next());Collections.sort(names);StringBuilder out=new StringBuilder("{");for(int i=0;i<names.size();i++){if(i>0)out.append(',');String n=names.get(i);out.append(JSONObject.quote(n)).append(':').append(canonicalValue(object.get(n)));}return out.append('}').toString();}
  private static String canonicalValue(Object value)throws JSONException{if(value instanceof JSONObject)return canonicalJson((JSONObject)value);if(value instanceof JSONArray){JSONArray a=(JSONArray)value;StringBuilder out=new StringBuilder("[");for(int i=0;i<a.length();i++){if(i>0)out.append(',');out.append(canonicalValue(a.get(i)));}return out.append(']').toString();}if(value==JSONObject.NULL)return"null";if(value instanceof String)return JSONObject.quote((String)value);if(value instanceof Boolean||value instanceof Number)return String.valueOf(value);throw new JSONException("Unsupported JSON value");}
  private static ApprovalRepository.ServerState parseState(JSONObject j)throws JSONException{long serverNowMs=j.getLong("serverNowMs");JSONArray requests=j.getJSONArray("requests"),devices=j.getJSONArray("devices"),allowances=j.getJSONArray("allowances");List<ApprovalRepository.Request>rs=new ArrayList<>();List<ApprovalRepository.Device>ds=new ArrayList<>();List<ApprovalRepository.Allowance>as=new ArrayList<>();for(int i=0;i<requests.length();i++)rs.add(parseRequest(requests.getJSONObject(i)));for(int i=0;i<devices.length();i++)ds.add(parseDevice(devices.getJSONObject(i)));for(int i=0;i<allowances.length();i++)as.add(parseAllowance(allowances.getJSONObject(i),serverNowMs));return new ApprovalRepository.ServerState(rs,ds,as,-1,serverNowMs,"","");}
  private static ApprovalRepository.Allowance parseAllowance(JSONObject j,long serverNowMs)throws JSONException{return new ApprovalRepository.Allowance(j.getString("pcId"),j.getString("gameId"),j.getString("ianaDay"),j.getString("ianaTimeZone"),j.getInt("totalSeconds"),j.getInt("committedSeconds"),j.getInt("reservedSeconds"),j.getLong("allowanceVersion"),serverNowMs);}
  private static ApprovalRepository.Request parseRequest(JSONObject o)throws JSONException{return new ApprovalRepository.Request(o.getString("requestId"),o.getString("childName"),o.getString("gameId"),o.getString("pcId"),o.getString("status"),o.isNull("personalDecision")?null:o.getString("personalDecision"),o.getLong("requestedAt"),o.getLong("expiresAt"),o.getInt("todayUsedMinutes"),o.getInt("todayLimitMinutes"));}
  private static ApprovalRepository.Device parseDevice(JSONObject o)throws JSONException{return new ApprovalRepository.Device(o.getString("id"),o.getString("name"),o.getString("platform"),o.getString("status"),o.getLong("registeredAt"));}
  private static String id(String value)throws ApiException{if(value==null||value.trim().isEmpty())throw new ApiException("ID is required");return Uri.encode(value);} private static ApiException apiError(String message,Exception cause){return cause instanceof ApiException?(ApiException)cause:new ApiException(message,cause);} public static class ApiException extends IOException{ApiException(String m){super(m);}ApiException(String m,Throwable c){super(m,c);}} public static final class ConflictException extends ApiException{private final int status;private final JSONObject current;ConflictException(String m,int status,JSONObject current){super(m);this.status=status;this.current=current;}public int getStatus(){return status;}public JSONObject getCurrent(){return current;}}
}
