name = "playtime-pact-remote-approval"
main = "src/worker.mjs"
compatibility_date = "2026-08-04"

[vars]
MINIMUM_PARENT_CLIENT_VERSION = "1"
[[d1_databases]]
binding = "DB"
database_name = "playtime-pact-remote-approval"
database_id = "00000000-0000-0000-0000-000000000000"

[triggers]
crons = ["*/1 * * * *"]
